"""
Seed script: 20 clientes latinos con su contacto primario (responsable).
Ejecutar desde la raíz del proyecto con el venv activo:
    python scripts/seed_clients.py
"""
import asyncio
import uuid
import asyncpg

DB_URL = "postgresql://postgres:Grvn240675$$@localhost:5432/crm"
ADMIN_USER_ID = "d06edc36-d03f-4960-864b-e71e8baee07b"

CLIENTS = [
    {
        "name": "Grupo Empresarial Alianza S.A.",
        "client_type": "company",
        "industry": "Consultoría",
        "website": "https://www.grupoalianza.cr",
        "phone": "+506 2290-1100",
        "email": "contacto@grupoalianza.cr",
        "country": "Costa Rica",
        "city": "San José",
        "address": "Barrio Escalante, Calle 37, Casa 452",
        "status": "active",
        "tax_id": "3-101-745231",
        "notes": "Cliente estratégico con contrato anual renovable.",
        "contact": {
            "full_name": "Ricardo Montoya Herrera",
            "position": "Gerente General",
            "email": "r.montoya@grupoalianza.cr",
            "phone": "+506 8890-2211",
            "whatsapp": "+506 8890-2211",
        },
    },
    {
        "name": "Tecnología Digital Latina S.R.L.",
        "client_type": "company",
        "industry": "Tecnología",
        "website": "https://www.tecdigitallatina.com",
        "phone": "+506 2234-5678",
        "email": "info@tecdigitallatina.com",
        "country": "Costa Rica",
        "city": "Heredia",
        "address": "Urbanización Los Álamos, Edificio Tech, Piso 3",
        "status": "active",
        "tax_id": "3-102-658901",
        "notes": "Empresa de desarrollo de software. Interesada en módulo de reportes.",
        "contact": {
            "full_name": "Sofía Vargas Ulate",
            "position": "Directora de Operaciones",
            "email": "s.vargas@tecdigitallatina.com",
            "phone": "+506 8812-3344",
            "whatsapp": "+506 8812-3344",
        },
    },
    {
        "name": "Inversiones Centroamérica Holdings",
        "client_type": "company",
        "industry": "Finanzas",
        "website": "https://www.icaholdings.com",
        "phone": "+502 2385-7700",
        "email": "gerencia@icaholdings.com",
        "country": "Guatemala",
        "city": "Ciudad de Guatemala",
        "address": "Zona 10, Edificio Empresarial Pradera, Nivel 8",
        "status": "prospect",
        "tax_id": "53261890-K",
        "notes": "Conocido por referido de Grupo Alianza. Primera reunión pendiente.",
        "contact": {
            "full_name": "Carlos Andrés Fuentes Paz",
            "position": "CEO",
            "email": "c.fuentes@icaholdings.com",
            "phone": "+502 5590-8800",
            "whatsapp": "+502 5590-8800",
        },
    },
    {
        "name": "Constructora Los Pinos S.A.",
        "client_type": "company",
        "industry": "Construcción",
        "website": "https://www.constructoralospinos.cr",
        "phone": "+506 2440-3300",
        "email": "admin@constructoralospinos.cr",
        "country": "Costa Rica",
        "city": "Alajuela",
        "address": "La Guácima, Costado norte del Aeropuerto Juan Santamaría",
        "status": "active",
        "tax_id": "3-101-830045",
        "notes": "Requiere facturación electrónica. Contacto principal muy puntual.",
        "contact": {
            "full_name": "Mauricio Jiménez Solano",
            "position": "Gerente Administrativo",
            "email": "m.jimenez@constructoralospinos.cr",
            "phone": "+506 8765-0011",
            "whatsapp": "+506 8765-0011",
        },
    },
    {
        "name": "Distribuidora El Mercado Tropical",
        "client_type": "company",
        "industry": "Distribución y Logística",
        "website": "https://www.mercadotropical.cr",
        "phone": "+506 2255-8800",
        "email": "ventas@mercadotropical.cr",
        "country": "Costa Rica",
        "city": "Cartago",
        "address": "Paraíso, Calle Principal, frente al ICE",
        "status": "inactive",
        "tax_id": "3-101-504812",
        "notes": "Pausó operaciones por reestructuración interna. Retomar contacto en Q3 2026.",
        "contact": {
            "full_name": "Ana Lucía Espinoza Mora",
            "position": "Jefa de Compras",
            "email": "a.espinoza@mercadotropical.cr",
            "phone": "+506 8923-4455",
            "whatsapp": None,
        },
    },
    {
        "name": "Agencia Creativa Fusión Digital",
        "client_type": "company",
        "industry": "Marketing y Publicidad",
        "website": "https://www.fusiondigital.cr",
        "phone": "+506 2200-9900",
        "email": "hola@fusiondigital.cr",
        "country": "Costa Rica",
        "city": "San José",
        "address": "Sabana Sur, Condominio Axis, Local 12",
        "status": "active",
        "tax_id": "3-102-901234",
        "notes": "Agencia joven con crecimiento acelerado. Requiere soporte mensual.",
        "contact": {
            "full_name": "Daniela Rojas Fernández",
            "position": "Directora Creativa",
            "email": "d.rojas@fusiondigital.cr",
            "phone": "+506 8801-6677",
            "whatsapp": "+506 8801-6677",
        },
    },
    {
        "name": "Importadora Pacífico Norte S.A.",
        "client_type": "company",
        "industry": "Importación y Exportación",
        "website": "https://www.pacificonorte.com",
        "phone": "+505 2270-4455",
        "email": "operaciones@pacificonorte.com",
        "country": "Nicaragua",
        "city": "Managua",
        "address": "Reparto Los Robles, Módulo B, Bodega 4",
        "status": "prospect",
        "tax_id": "J0310000085678",
        "notes": "Referido por ferias EXPOCOMER. Evaluando propuesta de módulo de inventario.",
        "contact": {
            "full_name": "Javier Enrique Ramos Solórzano",
            "position": "Gerente de Importaciones",
            "email": "j.ramos@pacificonorte.com",
            "phone": "+505 8880-3322",
            "whatsapp": "+505 8880-3322",
        },
    },
    {
        "name": "Clínica de Salud Integral Bienestar",
        "client_type": "company",
        "industry": "Salud",
        "website": "https://www.clinicabienestar.cr",
        "phone": "+506 2270-1500",
        "email": "recepcion@clinicabienestar.cr",
        "country": "Costa Rica",
        "city": "Escazú",
        "address": "Centro Comercial Multiplaza, Torre Empresarial, Piso 4",
        "status": "active",
        "tax_id": "3-101-672390",
        "notes": "Clínica con 12 especialidades. Requiere acceso para 5 usuarios adicionales.",
        "contact": {
            "full_name": "Laura Beatriz Chinchilla Arias",
            "position": "Administradora General",
            "email": "l.chinchilla@clinicabienestar.cr",
            "phone": "+506 8834-9900",
            "whatsapp": "+506 8834-9900",
        },
    },
    {
        "name": "Bufete Jurídico Sánchez & Asociados",
        "client_type": "company",
        "industry": "Servicios Legales",
        "website": "https://www.sanchezasociados.cr",
        "phone": "+506 2222-3344",
        "email": "info@sanchezasociados.cr",
        "country": "Costa Rica",
        "city": "San José",
        "address": "Barrio Amón, Avenida 9, Calle 3, Edificio Siglo XXI",
        "status": "active",
        "tax_id": "3-102-445678",
        "notes": "Bufete con 20 años en el mercado. Proceso de digitalización.",
        "contact": {
            "full_name": "Roberto Carlos Sánchez Mena",
            "position": "Socio Director",
            "email": "r.sanchez@sanchezasociados.cr",
            "phone": "+506 8856-7788",
            "whatsapp": None,
        },
    },
    {
        "name": "Exportaciones Café Verde S.A.",
        "client_type": "company",
        "industry": "Agro-exportación",
        "website": "https://www.cafeverde.cr",
        "phone": "+506 2441-6600",
        "email": "exportaciones@cafeverde.cr",
        "country": "Costa Rica",
        "city": "Naranjo",
        "address": "Finca La Esperanza, Ruta 35, Km 12",
        "status": "active",
        "tax_id": "3-101-298741",
        "notes": "Empresa familiar de tercera generación. Exportan a Europa y Asia.",
        "contact": {
            "full_name": "María Fernanda Quesada Blanco",
            "position": "Gerente de Exportaciones",
            "email": "mf.quesada@cafeverde.cr",
            "phone": "+506 8712-5544",
            "whatsapp": "+506 8712-5544",
        },
    },
    {
        "name": "Soluciones Financieras del Sur Ltda.",
        "client_type": "company",
        "industry": "Finanzas",
        "website": "https://www.sofinsur.com",
        "phone": "+57 601 789-4400",
        "email": "contacto@sofinsur.com",
        "country": "Colombia",
        "city": "Bogotá",
        "address": "Carrera 7 # 71-52, Torre A, Piso 10, Chapinero",
        "status": "prospect",
        "tax_id": "900234567-1",
        "notes": "Empresa colombiana en expansión a Centroamérica. Contacto frío por LinkedIn.",
        "contact": {
            "full_name": "Andrés Felipe Ospina Londoño",
            "position": "Director Comercial",
            "email": "a.ospina@sofinsur.com",
            "phone": "+57 310 456-7890",
            "whatsapp": "+57 310 456-7890",
        },
    },
    {
        "name": "Supermercados La Colonia del Este",
        "client_type": "company",
        "industry": "Comercio Minorista",
        "website": "https://www.lacoloniadeste.cr",
        "phone": "+506 2277-5500",
        "email": "gerencia@lacoloniadeste.cr",
        "country": "Costa Rica",
        "city": "San José",
        "address": "Curridabat, Avenida Central, frente al Hospital de La Católica",
        "status": "inactive",
        "tax_id": "3-101-112984",
        "notes": "Cadena en proceso de fusión. Proyecto pausado hasta resolución legal.",
        "contact": {
            "full_name": "Óscar Gerardo Villalobos Torres",
            "position": "Gerente de TI",
            "email": "o.villalobos@lacoloniadeste.cr",
            "phone": "+506 8890-0022",
            "whatsapp": "+506 8890-0022",
        },
    },
    {
        "name": "Instituto Educativo Latinoamérica",
        "client_type": "company",
        "industry": "Educación",
        "website": "https://www.ielatinoamerica.edu.cr",
        "phone": "+506 2250-8800",
        "email": "admisiones@ielatinoamerica.edu.cr",
        "country": "Costa Rica",
        "city": "Heredia",
        "address": "Santo Domingo, Edificio Universitario Central, 200m este del parque",
        "status": "active",
        "tax_id": "3-008-102345",
        "notes": "Instituto privado con 3,500 estudiantes. Requiere módulo de facturación por ciclos.",
        "contact": {
            "full_name": "Patricia Elena Solís Madrigal",
            "position": "Rectora",
            "email": "p.solis@ielatinoamerica.edu.cr",
            "phone": "+506 8823-1100",
            "whatsapp": None,
        },
    },
    {
        "name": "Hotel & Spa Las Brisas del Atlántico",
        "client_type": "company",
        "industry": "Turismo y Hotelería",
        "website": "https://www.lasbrisasatlantico.com",
        "phone": "+506 2750-1900",
        "email": "reservas@lasbrisasatlantico.com",
        "country": "Costa Rica",
        "city": "Limón",
        "address": "Cahuita, Playa Negra, km 3",
        "status": "prospect",
        "tax_id": "3-101-788234",
        "notes": "Hotel boutique con alta temporada en dic-abr. Contactado en feria EXPOTUR.",
        "contact": {
            "full_name": "Hansel Gerardo Mena Paniagua",
            "position": "Director de Operaciones",
            "email": "h.mena@lasbrisasatlantico.com",
            "phone": "+506 8745-3300",
            "whatsapp": "+506 8745-3300",
        },
    },
    {
        "name": "Logística Express Centroamérica",
        "client_type": "company",
        "industry": "Distribución y Logística",
        "website": "https://www.logexca.com",
        "phone": "+503 2540-7700",
        "email": "operaciones@logexca.com",
        "country": "El Salvador",
        "city": "San Salvador",
        "address": "Colonia Escalón, Pasaje Los Pinos #23",
        "status": "active",
        "tax_id": "0614-310890-109-0",
        "notes": "Maneja rutas CR, NI, HN, SV. Cliente recurrente con volumen alto.",
        "contact": {
            "full_name": "Ernesto Salvador Aguilar Rivas",
            "position": "Gerente Regional",
            "email": "e.aguilar@logexca.com",
            "phone": "+503 7890-4422",
            "whatsapp": "+503 7890-4422",
        },
    },
    {
        "name": "Desarrolladora Residencial Palmares",
        "client_type": "company",
        "industry": "Bienes Raíces",
        "website": "https://www.residencialpalmares.cr",
        "phone": "+506 2453-2200",
        "email": "ventas@residencialpalmares.cr",
        "country": "Costa Rica",
        "city": "Palmares",
        "address": "Centro de Palmares, Plaza Comercial del Valle, Local 4",
        "status": "active",
        "tax_id": "3-101-965412",
        "notes": "Desarrolla 2 condominios activos. Necesitan integración con sistema de cobros.",
        "contact": {
            "full_name": "Yessenia Paola Arce Jiménez",
            "position": "Gerente de Ventas",
            "email": "y.arce@residencialpalmares.cr",
            "phone": "+506 8867-5544",
            "whatsapp": "+506 8867-5544",
        },
    },
    {
        "name": "Servicios Ambientales GreenTech S.A.",
        "client_type": "company",
        "industry": "Medio Ambiente",
        "website": "https://www.greentechcr.com",
        "phone": "+506 2282-4400",
        "email": "info@greentechcr.com",
        "country": "Costa Rica",
        "city": "San José",
        "address": "Tres Ríos, Parque Empresarial Forum 1, Torre 3, Oficina 610",
        "status": "active",
        "tax_id": "3-102-714523",
        "notes": "Empresa de gestión de residuos y consultoría ambiental. Certificación ISO 14001.",
        "contact": {
            "full_name": "Alejandro José Méndez Castro",
            "position": "Director de Proyectos",
            "email": "a.mendez@greentechcr.com",
            "phone": "+506 8801-9988",
            "whatsapp": "+506 8801-9988",
        },
    },
    {
        "name": "Medios y Comunicaciones Caribe S.A.",
        "client_type": "company",
        "industry": "Medios de Comunicación",
        "website": "https://www.medioscaribe.com",
        "phone": "+506 2220-6600",
        "email": "comercial@medioscaribe.com",
        "country": "Costa Rica",
        "city": "San José",
        "address": "Rohrmoser, Avenida Las Palmas, Casa 14",
        "status": "inactive",
        "tax_id": "3-101-559872",
        "notes": "Grupo de medios con radio y TV. Presupuesto congelado hasta nuevo aviso.",
        "contact": {
            "full_name": "Diego Alonso Gamboa Robles",
            "position": "Gerente Comercial",
            "email": "d.gamboa@medioscaribe.com",
            "phone": "+506 8878-0033",
            "whatsapp": None,
        },
    },
    {
        "name": "Farmacéutica Nacional Salud Total",
        "client_type": "company",
        "industry": "Farmacéutica",
        "website": "https://www.saludtotal.cr",
        "phone": "+506 2239-3300",
        "email": "corporativo@saludtotal.cr",
        "country": "Costa Rica",
        "city": "San José",
        "address": "Pavas, Zona Industrial, Bodega 22-B",
        "status": "prospect",
        "tax_id": "3-101-400267",
        "notes": "Laboratorio nacional en licitación pública. Demo agendada para julio 2026.",
        "contact": {
            "full_name": "Ingrid Marcela Vega Porras",
            "position": "Gerente de Cadena de Suministro",
            "email": "i.vega@saludtotal.cr",
            "phone": "+506 8812-7766",
            "whatsapp": "+506 8812-7766",
        },
    },
    {
        "name": "Cooperativa Agrícola del Valle Central",
        "client_type": "company",
        "industry": "Agro-exportación",
        "website": "https://www.coopvallecentral.cr",
        "phone": "+506 2466-8800",
        "email": "administracion@coopvallecentral.cr",
        "country": "Costa Rica",
        "city": "San Carlos",
        "address": "Ciudad Quesada, Barrio El Carmen, diagonal a la Cruz Roja",
        "status": "active",
        "tax_id": "3-004-045321",
        "notes": "Cooperativa con 340 asociados. Proyecto piloto de trazabilidad en proceso.",
        "contact": {
            "full_name": "Wilberth Alonso Badilla Rojas",
            "position": "Presidente de Junta Directiva",
            "email": "w.badilla@coopvallecentral.cr",
            "phone": "+506 8723-4411",
            "whatsapp": "+506 8723-4411",
        },
    },
]


async def main():
    conn = await asyncpg.connect(DB_URL)
    try:
        async with conn.transaction():
            inserted = 0
            for c in CLIENTS:
                contact_data = c.pop("contact")
                client_id = uuid.uuid4()

                await conn.execute(
                    """
                    INSERT INTO clients (id, name, client_type, industry, website, phone, email,
                        country, city, address, status, tax_id, owner_user_id, notes)
                    VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14)
                    """,
                    client_id,
                    c["name"],
                    c["client_type"],
                    c["industry"],
                    c["website"],
                    c["phone"],
                    c["email"],
                    c["country"],
                    c["city"],
                    c["address"],
                    c["status"],
                    c["tax_id"],
                    uuid.UUID(ADMIN_USER_ID),
                    c["notes"],
                )

                await conn.execute(
                    """
                    INSERT INTO contacts (id, client_id, full_name, position, email, phone,
                        whatsapp, is_primary, is_active)
                    VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)
                    """,
                    uuid.uuid4(),
                    client_id,
                    contact_data["full_name"],
                    contact_data["position"],
                    contact_data["email"],
                    contact_data["phone"],
                    contact_data["whatsapp"],
                    True,
                    True,
                )

                inserted += 1
                print(f"  [{inserted:02d}] {c['name']} ({c['status']}) — {contact_data['full_name']}")

        print(f"\n✓ {inserted} clientes y contactos insertados correctamente.")
    finally:
        await conn.close()


if __name__ == "__main__":
    asyncio.run(main())
