"""
Seed script: 40 leads latinos con todos los campos.
Ejecutar desde la raíz del proyecto con el venv activo:
    python scripts/seed_leads.py
"""
import asyncio
import uuid
import asyncpg

DB_URL = "postgresql://postgres:Grvn240675$$@localhost:5432/crm"
ADMIN_USER_ID = "d06edc36-d03f-4960-864b-e71e8baee07b"

LEADS = [
    {
        "full_name": "Alejandro Pérez Gutiérrez",
        "company_name": "Grupo Pérez Hermanos S.A.",
        "email": "alejandro.perez@gpherms.com",
        "phone": "+506 2290-4411",
        "whatsapp": "+506 8810-4411",
        "source": "referral",
        "interest": "Sistema de gestión de ventas y CRM",
        "message": "Me recomendaron sus servicios, necesito automatizar el seguimiento de ventas de mi equipo de 15 personas.",
        "status": "qualified",
    },
    {
        "full_name": "María Isabel Rodríguez Fallas",
        "company_name": "Comercializadora Rodríguez e Hijos",
        "email": "mariaisabel@comercializadorarf.com",
        "phone": "+506 2234-7788",
        "whatsapp": "+506 8891-7788",
        "source": "website",
        "interest": "Módulo de cotizaciones y facturación",
        "message": "Visité su sitio web y me interesa el módulo de cotizaciones. Somos una empresa distribuidora con 8 vendedores.",
        "status": "contacted",
    },
    {
        "full_name": "Carlos Enrique Mora Vindas",
        "company_name": "Servicios Integrales Mora S.R.L.",
        "email": "cmora@simora.cr",
        "phone": "+506 2244-3300",
        "whatsapp": "+506 8823-3300",
        "source": "linkedin",
        "interest": "Gestión de oportunidades de negocio",
        "message": "Los encontré en LinkedIn. Tenemos un equipo comercial de 5 personas y necesitamos una herramienta de pipeline.",
        "status": "new",
    },
    {
        "full_name": "Luisa Fernanda Vargas Solano",
        "company_name": "Consultora LF Vargas & Co.",
        "email": "lvargas@lfvargasco.com",
        "phone": "+506 2256-9900",
        "whatsapp": None,
        "source": "email",
        "interest": "Reportes y analítica de ventas",
        "message": "Recibí un correo sobre sus soluciones. Soy consultora independiente y necesito herramientas de seguimiento de clientes.",
        "status": "new",
    },
    {
        "full_name": "Roberto Alonso Jiménez Brenes",
        "company_name": "Importaciones JB del Caribe S.A.",
        "email": "rjimenez@jbcaribe.com",
        "phone": "+506 2270-5566",
        "whatsapp": "+506 8856-5566",
        "source": "phone_call",
        "interest": "CRM completo para equipo de ventas",
        "message": "Llamé directamente porque estamos buscando reemplazar Excel por un CRM real. Somos importadores con clientes en 3 países.",
        "status": "qualified",
    },
    {
        "full_name": "Ana Patricia Salas Ureña",
        "company_name": "Asesoría Contable Salas",
        "email": "asalas@asesoriasalas.cr",
        "phone": "+506 2280-1122",
        "whatsapp": "+506 8901-1122",
        "source": "referral",
        "interest": "Módulo de tareas y seguimiento de clientes",
        "message": "Una colega me recomendó su plataforma. Tengo una firma de contabilidad pequeña y necesito organizar mis seguimientos.",
        "status": "contacted",
    },
    {
        "full_name": "Fernando José Cascante Alfaro",
        "company_name": "Construcciones Cascante S.A.",
        "email": "fcascante@const-cascante.cr",
        "phone": "+506 2441-8800",
        "whatsapp": "+506 8867-8800",
        "source": "facebook_ads",
        "interest": "Gestión de proyectos y clientes para constructora",
        "message": "Vi su anuncio en Facebook. Soy dueño de una constructora mediana y necesito controlar mis proyectos y clientes.",
        "status": "new",
    },
    {
        "full_name": "Verónica Liliana Herrera Picado",
        "company_name": "Distribuciones VH S.A.",
        "email": "vherrera@distribucionesVH.com",
        "phone": "+506 2255-3344",
        "whatsapp": "+506 8878-3344",
        "source": "instagram",
        "interest": "Sistema de ventas con seguimiento por WhatsApp",
        "message": "Los vi en Instagram. Distribuyo productos de belleza y necesito organizar mis vendedoras con seguimiento de clientes.",
        "status": "contacted",
    },
    {
        "full_name": "Jorge Luis Campos Benavides",
        "company_name": "Agencia Inmobiliaria Campos",
        "email": "jcampos@inmobcampos.cr",
        "phone": "+506 2222-6677",
        "whatsapp": "+506 8812-6677",
        "source": "website",
        "interest": "CRM para agencia inmobiliaria",
        "message": "Busqué en Google CRM para inmobiliarias. Tengo 10 asesores y necesito un pipeline de propiedades y clientes.",
        "status": "qualified",
    },
    {
        "full_name": "Paola Alejandra Solís Chaves",
        "company_name": "Diseños Solís Creativa",
        "email": "paola.solis@disolcreativa.cr",
        "phone": "+506 8834-2211",
        "whatsapp": "+506 8834-2211",
        "source": "linkedin",
        "interest": "Herramienta de gestión de clientes para freelancer",
        "message": "Soy diseñadora freelance y necesito llevar un control de mis proyectos y facturas. Vi tu perfil en LinkedIn.",
        "status": "new",
    },
    {
        "full_name": "Diego Mauricio Guzmán Pérez",
        "company_name": "Tech Solutions Guzmán S.A.",
        "email": "dguzman@techsolutions.cr",
        "phone": "+506 2290-7788",
        "whatsapp": "+506 8845-7788",
        "source": "referral",
        "interest": "Integración de CRM con ERP existente",
        "message": "Nos recomendó un cliente suyo. Somos empresa de TI y necesitamos integrar el CRM con nuestro sistema de facturación.",
        "status": "qualified",
    },
    {
        "full_name": "Silvia Estela Mora Portuguez",
        "company_name": "Clínica Dental Mora",
        "email": "smora@clinicadentalmora.cr",
        "phone": "+506 2225-9900",
        "whatsapp": "+506 8856-9900",
        "source": "whatsapp",
        "interest": "Gestión de citas y seguimiento de pacientes",
        "message": "Me escribí por WhatsApp porque necesito organizar mis citas y dar seguimiento a pacientes de ortodoncia.",
        "status": "contacted",
    },
    {
        "full_name": "Eduardo Rafael Vega Mora",
        "company_name": "Transportes Vega Express",
        "email": "evega@vegaexpress.com",
        "phone": "+506 2453-1100",
        "whatsapp": "+506 8790-1100",
        "source": "phone_call",
        "interest": "Control de flota y clientes de transporte",
        "message": "Llamé porque estamos creciendo y necesitamos digitalizar el control de rutas y clientes empresariales.",
        "status": "unqualified",
    },
    {
        "full_name": "Carmen Rosa Alfaro Quirós",
        "company_name": "Repostería Artesanal Dulce Vida",
        "email": "calfaro@dulcevida.cr",
        "phone": "+506 8923-4455",
        "whatsapp": "+506 8923-4455",
        "source": "instagram",
        "interest": "Sistema de pedidos y clientes para pastelería",
        "message": "Los vi en IG. Soy dueña de una repostería artesanal con pedidos por encargo y necesito organizarme mejor.",
        "status": "unqualified",
    },
    {
        "full_name": "Arturo Sebastián Brenes Acosta",
        "company_name": "Brenes Logística Internacional",
        "email": "abrenes@breneslogi.com",
        "phone": "+506 2277-4422",
        "whatsapp": "+506 8867-4422",
        "source": "email",
        "interest": "CRM para empresa de logística con clientes internacionales",
        "message": "Llegó una campaña de correo. Tenemos operaciones en CR, PAN y COL y necesitamos unificar la gestión de clientes.",
        "status": "qualified",
    },
    {
        "full_name": "Natalia Cristina Murillo Zamora",
        "company_name": "Eventos y Producción Murillo",
        "email": "nmurillo@eventosm.cr",
        "phone": "+506 2200-3311",
        "whatsapp": "+506 8812-3311",
        "source": "facebook_ads",
        "interest": "Gestión de eventos, cotizaciones y seguimiento",
        "message": "Vi el anuncio en Facebook. Organizo eventos corporativos y bodas. Necesito cotizar rápido y dar seguimiento.",
        "status": "new",
    },
    {
        "full_name": "Gustavo Adolfo Ramírez Solano",
        "company_name": "Ferretería Industrial Ramírez S.A.",
        "email": "gramírez@ferreind.cr",
        "phone": "+506 2460-5500",
        "whatsapp": "+506 8834-5500",
        "source": "referral",
        "interest": "Módulo de clientes y cotizaciones para ferretería",
        "message": "Referido por Constructora Los Pinos. Tengo ferretería industrial y quiero mejorar atención a clientes constructoras.",
        "status": "contacted",
    },
    {
        "full_name": "Daniela Sofía Castro Rojas",
        "company_name": "Studio Fotografía Castro",
        "email": "dcastro@fotografiacastro.com",
        "phone": "+506 8801-7744",
        "whatsapp": "+506 8801-7744",
        "source": "instagram",
        "interest": "Control de clientes y sesiones fotográficas",
        "message": "Me vieron en IG y les pregunté. Soy fotógrafa con estudio y necesito organizar reservas y pagos de clientes.",
        "status": "new",
    },
    {
        "full_name": "Manuel Antonio Quesada Ulate",
        "company_name": "Agrícola Los Naranjos S.A.",
        "email": "mquesada@losnaranjos.cr",
        "phone": "+506 2462-3300",
        "whatsapp": "+506 8778-3300",
        "source": "phone_call",
        "interest": "CRM para gestión de clientes agrícolas",
        "message": "Llamé porque exportamos piña y necesitamos llevar control de nuestros compradores internacionales.",
        "status": "qualified",
    },
    {
        "full_name": "Rebeca Tatiana Blanco Vásquez",
        "company_name": "Consultoría RH Blanco & Partners",
        "email": "rblanco@rhblancopartners.com",
        "phone": "+506 2256-8877",
        "whatsapp": None,
        "source": "linkedin",
        "interest": "Herramienta de gestión para firma de RRHH",
        "message": "Conecté por LinkedIn. Tengo una firma de recursos humanos y quiero llevar mejor el pipeline de clientes empresariales.",
        "status": "contacted",
    },
    {
        "full_name": "Héctor Miguel Espinoza Araya",
        "company_name": "Talleres Automotrices Espinoza",
        "email": "hespinoza@talleresespinoza.cr",
        "phone": "+506 2440-9988",
        "whatsapp": "+506 8890-9988",
        "source": "whatsapp",
        "interest": "Sistema de clientes y seguimiento para taller mecánico",
        "message": "Me contacté por WhatsApp. Tengo 2 talleres mecánicos y quiero llevar historial de servicios por cliente.",
        "status": "new",
    },
    {
        "full_name": "Lorena Beatriz Arias Méndez",
        "company_name": "Arias & Méndez Arquitectos",
        "email": "larias@ariasmendezcr.com",
        "phone": "+506 2290-0011",
        "whatsapp": "+506 8823-0011",
        "source": "website",
        "interest": "Gestión de proyectos y clientes para arquitectos",
        "message": "Entré a su web buscando CRM para arquitectos. Necesito controlar proyectos, cotizaciones y clientes.",
        "status": "qualified",
    },
    {
        "full_name": "Sebastián Andrés Torres Chacón",
        "company_name": "Media Digital Torres",
        "email": "storres@mediatd.cr",
        "phone": "+506 2211-4455",
        "whatsapp": "+506 8801-4455",
        "source": "facebook_ads",
        "interest": "CRM para agencia de marketing digital",
        "message": "Vi un anuncio en redes. Manejo una agencia de marketing y quiero automatizar el seguimiento de prospectos.",
        "status": "contacted",
    },
    {
        "full_name": "Adriana Marcela Núñez Barrantes",
        "company_name": "Joyería Artesanal Núñez",
        "email": "anunez@joyerianunez.com",
        "phone": "+506 2222-1133",
        "whatsapp": "+506 8867-1133",
        "source": "instagram",
        "interest": "Control de pedidos personalizados y clientes VIP",
        "message": "Me encontraron por IG. Tengo una joyería artesanal y necesito seguimiento de clientes corporativos y regalos.",
        "status": "unqualified",
    },
    {
        "full_name": "Ernesto Guillermo Picado Mora",
        "company_name": "Seguridad Privada Fortis S.A.",
        "email": "epicado@seguridadfortis.cr",
        "phone": "+506 2256-7788",
        "whatsapp": "+506 8845-7788",
        "source": "referral",
        "interest": "CRM para empresa de seguridad privada",
        "message": "Nos recomendaron. Somos empresa de seguridad con 60 guardas y necesitamos controlar contratos con clientes.",
        "status": "qualified",
    },
    {
        "full_name": "Gloria Patricia Leiva Sandoval",
        "company_name": "Centro Terapéutico Mente Sana",
        "email": "gleiva@mentesana.cr",
        "phone": "+506 2280-5566",
        "whatsapp": "+506 8912-5566",
        "source": "website",
        "interest": "Gestión de pacientes y citas para centro psicológico",
        "message": "Busqué en internet. Tengo un centro de psicología y necesito agendar citas y dar seguimiento a pacientes.",
        "status": "new",
    },
    {
        "full_name": "Marco Antonio Valverde Hidalgo",
        "company_name": "Panadería y Pastelería El Trigo Dorado",
        "email": "mvalverde@trigoadorado.cr",
        "phone": "+506 2250-9922",
        "whatsapp": "+506 8834-9922",
        "source": "whatsapp",
        "interest": "Sistema de pedidos y clientes para panadería",
        "message": "Me contacté por WhatsApp. Tengo 3 sucursales de panadería y quiero digitalizar pedidos de clientes empresariales.",
        "status": "contacted",
    },
    {
        "full_name": "Karla Vanessa Montero Delgado",
        "company_name": "Instituto de Belleza Klass",
        "email": "kmontero@institutoklass.cr",
        "phone": "+506 2234-6644",
        "whatsapp": "+506 8890-6644",
        "source": "facebook_ads",
        "interest": "Agenda de citas y base de clientes para salón de belleza",
        "message": "Vi publicidad en Facebook. Tengo un instituto de belleza con 8 estilistas y necesito organizar citas y clientes.",
        "status": "new",
    },
    {
        "full_name": "Ricardo Antonio Gamboa Vindas",
        "company_name": "Gamboa Ingeniería Civil S.A.",
        "email": "rgamboa@gamboaingenieria.cr",
        "phone": "+506 2441-0055",
        "whatsapp": "+506 8823-0055",
        "source": "linkedin",
        "interest": "Gestión de contratos y clientes para ingeniería",
        "message": "Conecté en LinkedIn. Soy ingeniero civil con empresa propia. Necesito controlar licitaciones y propuestas.",
        "status": "qualified",
    },
    {
        "full_name": "Yolanda Esperanza Ruiz Pérez",
        "company_name": "Servicios de Limpieza Ruiz S.A.",
        "email": "yruiz@limpiezaruiz.cr",
        "phone": "+506 2277-3344",
        "whatsapp": "+506 8878-3344",
        "source": "phone_call",
        "interest": "Control de contratos de limpieza y clientes",
        "message": "Llamé porque tenemos 40 empleados de limpieza y necesitamos organizar contratos con empresas clientes.",
        "status": "contacted",
    },
    {
        "full_name": "Alberto Enrique Mora Badilla",
        "company_name": "Finanzas y Crédito Mora S.A.",
        "email": "amora@financredito.com",
        "phone": "+506 2290-3322",
        "whatsapp": "+506 8801-3322",
        "source": "email",
        "interest": "CRM para financiera con cartera de clientes",
        "message": "Recibí la campaña de email. Tenemos una financiera con 800 clientes activos y necesitamos mejor seguimiento.",
        "status": "qualified",
    },
    {
        "full_name": "Stephanie Nicole Acosta Fonseca",
        "company_name": "Agencia de Viajes Costa Viajes",
        "email": "sacosta@costaviajes.cr",
        "phone": "+506 2222-8877",
        "whatsapp": "+506 8867-8877",
        "source": "instagram",
        "interest": "Gestión de clientes y cotizaciones para agencia de viajes",
        "message": "Me contacté por IG. Tengo una agencia de viajes y necesito hacer cotizaciones rápido y llevar historial de clientes.",
        "status": "new",
    },
    {
        "full_name": "Rodrigo Humberto Salazar Campos",
        "company_name": "Editorial Salazar Centroamérica",
        "email": "rsalazar@editorialsalazar.com",
        "phone": "+506 2255-1100",
        "whatsapp": None,
        "source": "referral",
        "interest": "CRM para editorial con clientes en toda CA",
        "message": "Nos recomendaron. Somos editorial con distribución en 6 países. Necesitamos CRM para libreros y distribuidoras.",
        "status": "unqualified",
    },
    {
        "full_name": "Mariela Gabriela Prado Arce",
        "company_name": "Centro Educativo Bilingüe Prado",
        "email": "mprado@cebprado.edu.cr",
        "phone": "+506 2250-0044",
        "whatsapp": "+506 8823-0044",
        "source": "website",
        "interest": "Módulo de alumnos y seguimiento de admisiones",
        "message": "Entré a su web. Dirijo un colegio bilingüe privado con 400 estudiantes. Quiero mejorar el proceso de admisiones.",
        "status": "contacted",
    },
    {
        "full_name": "José Ángel Bermúdez Vega",
        "company_name": "Equipos Médicos Bermúdez S.A.",
        "email": "jbermudez@equimedber.com",
        "phone": "+506 2234-7711",
        "whatsapp": "+506 8856-7711",
        "source": "linkedin",
        "interest": "CRM para distribuidora de equipos médicos",
        "message": "Vi perfil de empresa en LinkedIn. Distribuimos equipos médicos a clínicas y necesitamos seguimiento de ventas.",
        "status": "qualified",
    },
    {
        "full_name": "Claudia Viviana Morales Zúñiga",
        "company_name": "Nutrición y Vida Sana Morales",
        "email": "cmorales@nutrivida.cr",
        "phone": "+506 8801-5533",
        "whatsapp": "+506 8801-5533",
        "source": "whatsapp",
        "interest": "Control de pacientes y planes nutricionales",
        "message": "Me escribí por WhatsApp. Soy nutricionista con consultorio privado y clientes empresariales de bienestar.",
        "status": "new",
    },
    {
        "full_name": "Andrés Mauricio Herrera Madrigal",
        "company_name": "Publicidad Exterior Herrera S.A.",
        "email": "aherrera@pubexterior.cr",
        "phone": "+506 2270-6655",
        "whatsapp": "+506 8878-6655",
        "source": "facebook_ads",
        "interest": "Sistema para gestionar contratos de vallas publicitarias",
        "message": "Vi campaña en Facebook. Tengo una empresa de vallas y rótulos, necesito gestionar contratos con clientes.",
        "status": "contacted",
    },
    {
        "full_name": "Isabel Lucía Ulate Fonseca",
        "company_name": "Textiles Ulate & Moda S.A.",
        "email": "iulate@textilesulate.com",
        "phone": "+506 2260-4433",
        "whatsapp": "+506 8845-4433",
        "source": "referral",
        "interest": "Gestión de pedidos B2B para empresa textil",
        "message": "Referida por una clienta. Tengo empresa textil que vende a tiendas y boutiques. Necesito controlar pedidos.",
        "status": "qualified",
    },
    {
        "full_name": "Francisco Javier Chaves Rodríguez",
        "company_name": "Materiales para Construcción Chaves",
        "email": "fchaves@matconsychaves.cr",
        "phone": "+506 2452-8833",
        "whatsapp": "+506 8867-8833",
        "source": "phone_call",
        "interest": "CRM para distribuidora de materiales de construcción",
        "message": "Llamé directamente. Distribuyó materiales a constructoras y contratistas. Necesito controlar crédito y seguimiento.",
        "status": "new",
    },
    {
        "full_name": "Priscila Marcela Aguilar Calvo",
        "company_name": "Marketing de Contenidos Praxis",
        "email": "paguilar@marketingpraxis.cr",
        "phone": "+506 2201-3300",
        "whatsapp": "+506 8812-3300",
        "source": "email",
        "interest": "Herramienta de seguimiento para agencia de contenidos",
        "message": "Llegó un correo de campaña. Tengo agencia de contenidos con 15 clientes activos y necesito automatizar reportes.",
        "status": "contacted",
    },
]


async def main():
    conn = await asyncpg.connect(DB_URL)
    try:
        async with conn.transaction():
            inserted = 0
            for lead in LEADS:
                lead_id = uuid.uuid4()
                await conn.execute(
                    """
                    INSERT INTO leads (id, full_name, company_name, email, phone, whatsapp,
                        source, interest, message, status, assigned_user_id)
                    VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)
                    """,
                    lead_id,
                    lead["full_name"],
                    lead["company_name"],
                    lead["email"],
                    lead["phone"],
                    lead["whatsapp"],
                    lead["source"],
                    lead["interest"],
                    lead["message"],
                    lead["status"],
                    uuid.UUID(ADMIN_USER_ID),
                )
                inserted += 1
                print(f"  [{inserted:02d}] {lead['full_name']} | {lead['status']:12s} | {lead['source']:15s} | {lead['company_name'] or '(freelancer)'}")

        print(f"\n✓ {inserted} leads insertados correctamente.")
    finally:
        await conn.close()


if __name__ == "__main__":
    asyncio.run(main())
